export const GET_HUMANS_START = 'GET_HUMANS_START';
export const GET_HUMANS_SUCCESS = 'GET_HUMANS_SUCCESS';
export const GET_HUMANS_ERROR = 'GET_HUMANS_ERROR';
export const DELETE_HUMAN_START = 'DELETE_HUMAN_START';
export const DELETE_HUMAN_SUCCESS = 'DELETE_HUMAN_SUCCESS';
export const DELETE_HUMAN_ERROR = 'DELETE_HUMAN_ERROR';
