export const EDIT_HUMAN_START = 'EDIT_HUMAN_START';
export const EDIT_HUMAN_SUCCESS = 'EDIT_HUMAN_SUCCESS';
export const EDIT_HUMAN_ERROR = 'EDIT_HUMAN_ERROR';
export const GET_HUMAN_START = 'GET_HUMAN_START';
export const GET_HUMAN_SUCCESS = ' GET_HUMAN_SUCCESS';
export const GET_HUMAN_ERROR = 'GET_HUMAN_ERROR'